from enum import Enum

class TYPES(Enum):
    NOUN_SUPERSENSE = 'noun_supersense'
    VERB_SUPERSENSE = 'verb_supersense'
    PREPOSITION_SUPERSENSE = 'preposition_supersense'

NOUN_SUPERSENSES = (
    'ANIMAL',
    'ARTIFACT',
    'ATTRIBUTE',
    'ACT',
    'COGNITION',
    'COMMUNICATION',
    'BODY',
    'EVENT',
    'FEELING',
    'FOOD',
    'GROUP',
    'LOCATION',
    'MOTIVE',
    'OBJECT',
    'OTHER',
    'PERSON',
    'PHENOMENON',
    'PLANT',
    'POSSESSION',
    'PROCESS',
    'QUANTITY',
    'RELATION',
    'SHAPE',
    'STATE',
    'SUBSTANCE',
    'TIME',
)

VERB_SUPERSENSES = (
    'body',
    'change',
    'cognition',
    'communication',
    'competition',
    'consumption',
    'contact',
    'creation',
    'emotion',
    'motion',
    'perception',
    'possession',
    'social',
    'stative',
)

PREPOSITION_SUPERSENSES = (
    '1DTrajectory',
    '2DArea',
    'Accompanier',
    'Activity',
    'Age',
    'Agent',
    'Approximator',
    'Attribute',
    'Beneficiary',
    'Causer',
    'Circumstance',
    'ClockTimeCxn',
    'Co-Agent',
    'Co-Participant',
    'Co-Theme',
    'Comparison/Contrast',
    'Contour',
    'Course',
    'DeicticTime',
    'Destination',
    'Direction',
    'Donor/Speaker',
    'Duration',
    'Elements',
    'EndState',
    'EndTime',
    'Experiencer',
    'Explanation',
    'Extent',
    'Frequency',
    'Function',
    'Goal',
    'InitialLocation',
    'Instance',
    'Instrument',
    'Location',
    'Locus',
    'Manner',
    'Material',
    'Means',
    'Patient',
    'Possessor',
    'ProfessionalAspect',
    'Purpose',
    'Quantity',
    'Recipient',
    'Reciprocation',
    'RelativeTime',
    'Scalar/Rank',
    'Source',
    'Species',
    'StartState',
    'StartTime',
    'State',
    'Stimulus',
    'Superset',
    'Theme',
    'Time',
    'Topic',
    'Value',
    'ValueComparison',
    'Via',
    'Whole'
)

