from .spacy_ner import SPACY_NER
from .preps import PREPS
from .ud_pos import UD_POS
from .spacy_pos import SPACY_POS
from .pss import PSS
from .spacy_deps import SPACY_DEPS
from .tokens import TOKENS
from .ud_deps import UD_DEPS
from .boolean import BOOLEAN